title: Abhishek's Blog
author:
  name: Abhishek Dutt
  email: abhishekdutt@outlook.com
description: > # this means to ignore newlines until "show_excerpts:"
  Thanks for stopping by!

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: _AbhishekDutt01
    github:  AbhishekDutt
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: abhishek.dutt
    linkedin: abhishekdutt01
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima
minima:
  skin: classic
  # skin: dark  

plugins:
 - jekyll-feed
 - jekyll-seo-tag

disqus:
  shortname: abhisheks-blog

url: https://abhishekdutt.github.io/
baseurl: /blog